version: '3.4'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=$DBUSER
      - INFLUXDB_ADMIN_PASSWORD=$DBPASSWORD
volumes: 
  influxdb-storage: